#### SAEZ, Eljenzal Hoper U. 

## *Normalization Problem*

Generate a random 5x5 array, normalize it, and save the result as X_normalized.npy.

In [5]:
import numpy as np

# creating a random 5x5 ndarray
X = np.random.rand(5, 5)

# calculate the mean and standard deviation
mean = X.mean()
std_dev = X.std()

# normalize the array using the given formula
X_normalized = (X - mean) / std_dev

# save the normalized array to a file
np.save('X_normalized.npy', X_normalized)

# print the results
print("Original Array:\n", X)
print("\nNormalized Array:\n", X_normalized)  # added \n for spacing

Original Array:
 [[0.0273946  0.82568946 0.14118158 0.74282425 0.91215933]
 [0.09323498 0.24676741 0.57522548 0.33489202 0.68612467]
 [0.25871198 0.90800563 0.82335865 0.60178136 0.55191473]
 [0.39703248 0.79994896 0.17297976 0.51994781 0.84180587]
 [0.59933276 0.69099047 0.3802607  0.82692102 0.8097321 ]]

Normalized Array:
 [[-1.92362181  1.01067456 -1.50537447  0.70608647  1.32851229]
 [-1.68161201 -1.11727212  0.09004284 -0.79335202  0.49767556]
 [-1.07336739  1.31324448  1.00210718  0.18765444  0.00435941]
 [-0.56494202  0.91606005 -1.38849373 -0.11314154  1.06991373]
 [ 0.17865411  0.51556081 -0.62659015  1.01520139  0.95201998]]


## *Division by 3 Problem*

Create a 10x10 array of squared numbers from 1 to 100, extract those divisible by 3, and save them as div_by_3.npy.

In [12]:
import numpy as np  # import numpy

# make a 10x10 array with squares of numbers 1 to 100
X = np.arange(1, 101).reshape(10, 10) ** 2

# get the elements divisible by 3
divisible = X[X % 3 == 0]

# save the result
np.save("div_by_3.npy", divisible)

# print results
print("Original Array:\n", X)
print("\nElements Divisible by 3:\n", divisible)

Original Array:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
